name: Website CI (test.datacore.app)

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build project
      env:
        GATSBY_DATACORE_URL: https://test.datacore.app/
        GATSBY_ASSETS_URL: https://assets.datacore.app/
      run: |
        npm install
        npm run build
    - name: Publish to server via rsync
      run: |
        sudo apt-get update -y -qq
        sudo apt-get install -y -qq sshpass rsync
        mkdir -p ~/.ssh
        touch ~/.ssh/known_hosts
        ssh-keyscan -p 1337 ${{ secrets.RSYNC_HOST }} >> ~/.ssh/known_hosts
        sshpass -p "${{ secrets.RSYNC_PASS }}" rsync -avz -e 'ssh -p 1337' --progress --delete ./public/ ${{ secrets.RSYNC_USER }}@${{ secrets.RSYNC_HOST }}:/sitebuild/
